- README.md
Since PHPStan would be used only during development it's better to have it as a dev dependency.
> Add "--dev" flag to "composer require" command.

- src/Reflection/PhpDefect/PhpDefectClassReflectionExtension.php
- tests/PHPStan/Reflection/PhpDefect/PhpDefectClassReflectionExtensionTest.php
So. I noticed it says that properties of DateInterval are undefined. But did I update the test correctly? Who knows... Also, this PR only includes updated test. Honestly, I have no Idea how to fix it.
> Add DateInterval properties test

- build/phpstan.neon
- conf/config.neon
- src/Broker/BrokerFactory.php
- src/Reflection/Annotations/AnnotationMethodReflection.php
- src/Reflection/Annotations/AnnotationsMethodsClassReflectionExtension.php
- src/Type/FileTypeMapper.php
- tests/PHPStan/Reflection/Annotations/AnnotationsMethodsClassReflectionExtensionTest.php
- tests/PHPStan/Reflection/Annotations/data/annotations-methods.php
Add partial support for methods defined by @method annotations. Parse name and return type of methods. Parametes are (for now) ignored so all function defined by annotations are variadic.
> Add partial support for methods defined by @method annotations

- composer.json
This change allows using phpstan with Laravel's LTS version 5.1
As far as I can tell you're not using anything that is not available in symfony/{console,finder} 2.7
> Loosen dependency version constraints.

- src/Type/FileTypeMapper.php
- src/Type/TypehintHelper.php
- tests/PHPStan/Rules/Methods/ReturnTypeRuleTest.php
- tests/PHPStan/Rules/Methods/data/returnTypes.php
PHPStan looks great and it already allowed me to find a potential bug. Thanks!
However I've found a false positive while scanning the [API Platform](https://api-platform.com) code base:
```
------ -------------------------------------------------------------------------------------------------------------------------------------------------------------- 
Line   src/Hal/Serializer/CollectionNormalizer.php                                                                                                                   
------ -------------------------------------------------------------------------------------------------------------------------------------------------------------- 
55     Return typehint of method ApiPlatform\Core\Hal\Serializer\CollectionNormalizer::normalize() has …
```
> Add support for the "scalar" pseudo type

- src/Command/AnalyseCommand.php
To allow loading custom extensions & setting up memory limit from phpstan.neon.
> Enable PhpExtension & ExtensionsExtension by default

- src/Reflection/Annotations/AnnotationsMethodsClassReflectionExtension.php
- src/Type/FileTypeMapper.php
- tests/PHPStan/Reflection/Annotations/AnnotationsMethodsClassReflectionExtensionTest.php
- tests/PHPStan/Reflection/Annotations/data/annotations-methods.php
Fix https://github.com/phpstan/phpstan/issues/193
There are 2 signatures that cannot be parsed appropriately without some
more thought:
```
* @method IsThisTheMethodNameOrReturnType IsThisTheMethodNameOrTheFirstWordOfTheDescription IsThisTheFirstOrSecondWordOfTheDescription
* @method static IsThisTheStaticMethodNameOrReturnType IsThisTheStaticMethodNameOrTheFirstWordOfTheDescription IsThisTheFirstOrSecondWordOfTheDescription
```
> Support docblock method signatures without parenthesise

- README.md
The documentation has an example with the command line option "errorFormatter" however the option is actually "errorFormat"
> corrected name of option in docs

- src/Rules/Functions/PrintfParametersRule.php
- tests/PHPStan/Rules/Functions/data/printf.php
Fixed [`printf`](http://php.net/manual/en/function.sprintf.php) parameters rule to support optional precision specifier.
> An optional precision specifier in the form of a period (.) followed by an **_optional_** decimal digit string that says how many decimal digits should be displayed for floating-point numbers.
> Fix printf parameters rule.

- README.md
I understand that the neon config format supports tabs, but as the yaml
syntax highlighter is used for examples, it renders ugly red blocks
instead of tabs.
On the other hand, if someone copies the snippet to his config file, he
will get spaces instead of tabs, so I'm not sure which is better.
> README: use spaces instead of tabs in config examples

- src/Command/AnalyseCommand.php
I've added a `PHPSTAN_TEMP_DIR` environment variable, that works nicely for now. But I'd also like some automatic fallback to system temp directory, to not break existing workflows.
Required for [phpstan-compiler](https://github.com/fprochazka/phpstan-compiler#phpstan-phar-compiler), depends on #249
> FileHelper resolves temp dir when phpstan is packed in phar

- src/Analyser/Scope.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
Change in commit https://github.com/phpstan/phpstan/commit/3d60b7c7ad363519f98abef605a54fdcef52df2b doesn't take into account a situation when a single array is passed to `min()` or `max()`.
From: http://php.net/min:
> If the first and only parameter is an array, min() returns the lowest value in that array. 
The fix is not perfect, because if in the future, more functions are added into `$functionsThatCombineAllArgumentTypes`, they may behave differently. Would you prefer wrapping the condition in another one which would check specifically for min/max?
> min and max behave differently for single array argument

- src/File/FileExcluder.php
- tests/PHPStan/File/FileExcluderTest.php
Otherwise running phpstan on itself fails when run in cmd opened with `c:` instead of `C:`.
They had similar issue in VSCode https://github.com/Microsoft/vscode/issues/9448
> FileExcluder should match case-insensitively on Windows

- src/Rules/FunctionCallParametersCheck.php
- tests/PHPStan/Rules/Methods/CallMethodsRuleTest.php
- tests/PHPStan/Rules/Methods/data/mysqli-query.php
Workaround for parameters check of mysqli::query call (needed because ReflectionMethod::getParameters() returns only 1 parameter for mysqli::query instead of 2 (see https://bugs.php.net/bug.php?id=74595)).
> Fixed mysqli::query parameters count

- conf/config.neon
- src/Command/ErrorFormatter/CheckstyleErrorFormatter.php
- src/Command/ErrorsConsoleStyle.php
- tests/PHPStan/Command/ErrorFormatter/CheckstyleErrorFormatterTest.php
Enabled PHPStan to create reports in checkstyle.xml format #271.
Support for this format is currently limited: all violations have a severity of "error".
All violations are marked as found in column 1.
> Checkstyle formatter

- src/Analyser/Scope.php
- src/Analyser/SpecifiedTypes.php
- src/Analyser/TypeSpecifier.php
- tests/PHPStan/Analyser/TypeSpecifierTest.php
I finally figured out, how to write `TypeSpecifier` without passing `$types` and `$source` all the time. This makes the whole code a lot simpler.
It also included commented out code for intersection types, once they are ready.
> TypeSpecifier: fixed some cases & refactoring

- src/Rules/Methods/CallMethodsOnPossiblyNullRule.php
- tests/PHPStan/Rules/Methods/CallMethodsOnPossiblyNullRuleTest.php
Hi.
Just a little semantic change to the error description.  We already know the type is "possibly nullable" so that information is unnecessary, plus we really don't call anything on a *type* but rather a *value*.
Great job implementing this check by the way, love it!
> Add better description to "call on nullable" error

- src/Rules/Classes/RequireParentConstructCallRule.php
- tests/PHPStan/Rules/Classes/data/call-to-parent-constructor.php
I found a bug that prevented RequireParentConstructCallRule to detect suppressed calls (@parent::__construct()). I fixed the bug & updated the unit test.
> RequireParentConstructCallRule fix: supressed constructor calls are now detected correctly

- src/Reflection/Annotations/AnnotationMethodReflection.php
- src/Reflection/Annotations/AnnotationPropertyReflection.php
- src/Reflection/Annotations/AnnotationsMethodParameterReflection.php
- src/Reflection/Annotations/AnnotationsMethodsClassReflectionExtension.php
- src/Reflection/Annotations/AnnotationsPropertiesClassReflectionExtension.php
- src/Reflection/Php/PhpPropertyReflection.php
- src/Reflection/Php/UniversalObjectCrateProperty.php
- src/Reflection/PhpDefect/PhpDefectPropertyReflection.php
- src/Reflection/PhpParser/NamespacedNameProperty.php
- src/Reflection/PropertyReflection.php
- src/Type/FileTypeMapper.php
- tests/PHPStan/Reflection/Annotations/AnnotationsMethodsClassReflectionExtensionTest.php
- tests/PHPStan/Reflection/Annotations/AnnotationsPropertiesClassReflectionExtensionTest.php
- tests/PHPStan/Reflection/Annotations/data/annotations-methods.php
- tests/PHPStan/Reflection/Annotations/data/annotations-properties.php
1. I am not sure why to write-only properties are omitted but let me know if there is a reason to keep it that way.
2. Parsing nullable types using a question mark (`?`) for all annotations is not implemented in general type regexp. I am thinking if it makes sense or not. It makes sense for method annotation parameters IMHO. However, I am not sure about general annotations because using `type|null` is used generally. On the other hand, without implementing it there is a problem with type map that does not have the type used in method annotation as method parameter type only (without any other reference) and then the type is assumed as mixed.
I will update this PR by comments.
> Improvement of parsing class annotations - write only properties, method parameters

- src/Reflection/Php/PhpMethodReflection.php
- tests/PHPStan/Rules/Methods/CallMethodsRuleTest.php
- tests/PHPStan/Rules/Methods/data/call-trait-overridden-methods.php
This fixes a bug in the PHP scripting engine, which causes
Reflection API to return the incorrect case for aliased methods
when traits are nested.
Fixes #379
This is an alternative implementation to PR #380, as requested.
> Fix "incorrect case" error when using trait aliases

- src/Reflection/Annotations/AnnotationsMethodsClassReflectionExtension.php
- src/Type/FileTypeMapper.php
- tests/PHPStan/Reflection/Annotations/AnnotationsMethodsClassReflectionExtensionTest.php
- tests/PHPStan/Reflection/Annotations/AnnotationsPropertiesClassReflectionExtensionTest.php
- tests/PHPStan/Reflection/Annotations/data/annotations-methods.php
- tests/PHPStan/Reflection/Annotations/data/annotations-properties.php
- tests/PHPStan/Type/FileTypeMapperTest.php
- tests/PHPStan/Type/data/annotations.php
It is used in some libraries, for example, older version of OAuth2 server from PHP League https://github.com/thephpleague/oauth2-server/blob/4.1.6/src/Storage/AccessTokenInterface.php
> Fixed parsing multiple types with extra spaces around pipe character

- bin/phpstan
- composer.json
I've noticed that from CLI it says "Unknown version". With this PR I want to improve that.
Full disclosure: I'm the author of the `jean85/pretty-package-versions` package added with this PR. It's only a very thin wrapper for ocramius/pretty-package-versions.
In this way, the CLI will either show:
PHPStan - PHP Static Analysis Tool 0.8.9999999.9999999-dev@262909a
or, if it's a tagged version, the prettier
PHPStan - PHP Static Analysis Tool 0.8.1
PS: I would suggest to you to slowly migrate this project toward PSR-2, any other bigger contribution would be really harder to be done.
> Show pretty version in CLI

- composer.json
- phpcs.xml
There are two new sniffs in the Slevomat CS repo as of [3.3.0](https://github.com/slevomat/coding-standard/releases/tag/3.3.0), which were not part of the standard, but there is AFAIK no easy way currently to exclude them from the standard, that is defining them.
More long term solution will require probably a major release in Slevomat CS.
This is currently breaking builds here, see for example #469:
https://travis-ci.org/phpstan/phpstan/jobs/268627720#L565
> Exclude new sniffs from the Slevomat CS, which were not part of the standard

- src/Type/TypehintHelper.php
There is a a little used meta type, ['number'][docs], which is the
union of int and float. It's not part of PHPDoc, however it is used in
[interfaces generated from the PHP SPL documentation][eg-1] and
[interfaces that offer polyfils][eg-2].
It's used in the PHP SPL for [NumberFormatter::format][format], possibly
other places too.
[eg-1]: https://github.com/JetBrains/phpstorm-stubs/blob/master/intl/intl.php#L920
[eg-2]: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Intl/NumberFormatter/NumberFormatter.php#L371
[format]: http://www.php.net/manual/en/numberformatter.format.php
[docs]: https://secure.php.net/manual/en/language.pseudo-types.php#language.types.number
> Add support for number type

- src/Type/FileTypeMapper.php
- tests/PHPStan/Type/FileTypeMapperTest.php
- tests/PHPStan/Type/data/annotations.php
minor fix, issue discovered when testing code provided by @Majkl578
> FileTypeMapper: fix type pattern to support class names with length 1

- .editorconfig
If a glob pattern contains braces (`{}`) and there isn't any comma in between them, the pattern isn't considered to be a list with only one item but braces are part of the expected string (see [editorconfig/editorconfig-core-test](https://github.com/editorconfig/editorconfig-core-test/tree/172eb8324225f09f3e331af26454a5b45e314edb/glob)). 
Therefore, `[*.{xml}]` matched eg. `foo.{xml}` but not `foo.xml` or `phpunit.xml`.
> Fix glob patterns in .editorconfig

- README.md
- build/PHPStan/Build/ServiceLocatorDynamicReturnTypeExtension.php
- src/Type/DynamicMethodReturnTypeExtension.php
- src/Type/DynamicStaticMethodReturnTypeExtension.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
Relates to #593 and #163.
This PR changes the `getClass()` methods of the `DynamicFunctionReturnTypeExtension` and `DynamicStaticMethodReturnTypeExtension` interfaces to be non-static, which facilitates registration of the same extension for multiple class names via DI configuration.
Note that the build will fail because there is a dev dependency on `phpstan/phpstan-phpunit`, which implements these interfaces. I can't do much about that right now, because it's a circular dependency.
There's also some diff churn due to trailing whitespace, which my editor trims automatically. Let me know if this is a problem.
> Change dynamic return type interface getClass() methods to be non-static

- composer.json
The original issue was reported in https://github.com/Jean85/pretty-package-versions/issues/3
Basically, the version shown in the PHAR was normalized, so `0.8.5.0` instead of the correct `0.8.5`. This version bump will fix the issue.
> Fix version shown in the PHAR

- tests/PHPStan/Analyser/NodeScopeResolverTest.php
- tests/PHPStan/Command/ErrorFormatter/CheckstyleErrorFormatterTest.php
- tests/PHPStan/Reflection/Annotations/AnnotationsMethodsClassReflectionExtensionTest.php
`assertEquals()` does not compare strictly, so it may hide bugs.
> Use assertSame() instead of assertEquals() in tests

- composer.json
PHPStan require some php extension to execute tests:
- `locale_get_display_language`
- `mysqli_fetch_all`
- `imagepng`
Some of them should be missing (due to missing php extensions) and tests fails.
Adding:
- `ext-gd`
- `ext-intl`
- `ext-mysqli`
into `composer.json` (`require-dev` section) allow users to know that are required in order to run tests.
> refs #TECH: declare php extensions required in tests

- appveyor.yml
`master` branch no longer supports PHP 7.0, so it should be removed.
> Fix AppVeyor CI build

- README.md
- src/Command/AnalyseCommand.php
- src/DependencyInjection/Configurator.php
- src/DependencyInjection/ContainerFactory.php
- src/DependencyInjection/LoaderFactory.php
- tests/PHPStan/Command/AnalyseCommandTest.php
- tests/PHPStan/Command/test-autodiscover-dist/phpstan.neon.dist
- tests/PHPStan/Command/test-autodiscover-priority/phpstan.neon
- tests/PHPStan/Command/test-autodiscover-priority/phpstan.neon.dist
- tests/PHPStan/Command/test-autodiscover/phpstan.neon
Allow auto-discovery of phpstan.neon and phpstan.neon.dist files.
Closes #237.
Tests should be green, I'll add more covering this change once this feature is given green.
> Auto-discover phpstan.neon{,.dist} config files

- README.md
- src/Command/AnalyseApplication.php
- src/Command/AnalyseCommand.php
This change allows level and paths be specified in custom configuration file, without the need to specify those as CLI option/argument.
Example:
```yaml
parameters:
level: 5
paths:
- %currentWorkingDirectory%/src
```
It does **not** override arguments specified explicitly on input.
Tests should be green, I'll add more covering this change once this feature is given green.
> Allow paths and level be specified in config

- src/Analyser/NodeScopeResolver.php
- src/Analyser/Scope.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
- tests/PHPStan/Analyser/data/early-termination-defined.php
- tests/PHPStan/Analyser/data/early-termination.php
While trying to get phpstan to register a static call to `PHPUnit\Framework\TestCase::fail` as an early terminating method, I realised that it just ignores all static methods for early termination. By the time I understood the source enough to realise I could have just called the static method dynamically, I'd already spent a while on it and figured I might as well update the source to support static methods.
I've updated the tests to include a check for a static early terminating function, and also tested it in my own project and everything seems to be working well.
> Allow early terminating static calls

- README.md
The `BrokerAwareClassReflectionExtension` interface is now deprecated in favour of `BrokerAwareExtension` since 0.9.
> Rename deprecated interface in docs

- bin/phpstan
With this branch the error message become:
```
./bin/phpstan asd
Command "asd" is not defined.
```
Before was something like:
```
./bin/phpstan asd
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\CommandNotFoundException: Command "asd" is not defined. in /Users/fain182/Documents/OpenSource/phpstan/vendor/symfony/console/Application.php:611
Stack trace:
#0 /Users/fain182/Documents/OpenSource/phpstan/vendor/symfony/console/Application.php(224): Symfony\Component\Console\Application->find('asd')
#1 /Users/fain182/Documents/OpenSource/phpstan/vendor/symfony/console/Application.php(143): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 …
```
> Improve error message for command not found

- src/TrinaryLogic.php
I've tried to run PHPStan on Drupal 8 codebase and my laptop dies.
I am suspecting it ran out of memory and I know the code base has never been tested with the tool, so there are likly many errors.
I saw that the tool was running without a garbage collection.
So this is a small step to improve my particular memory usage problems.
**Offtopics:** 
Why the GC is disabled?
Is there a runtime option to enable it?
> Micro-optimisation to prevent excessive memory allocation

- tests/PHPStan/Rules/Functions/CallToFunctionParametersRuleTest.php
With commit https://github.com/phpstan/phpstan/commit/24894eb the check for `unpack` response error is splitted on two different test for PHP < 7.1.1 and PHP >= 7.1.1 but the version check condition is missing in one test.
We have failure on master and all branches that we generate from it, see: 
- https://ci.appveyor.com/project/ondrejmirtes/phpstan/build/1225/job/baub4tyma3rqwisn#L244
- https://ci.appveyor.com/project/ondrejmirtes/phpstan/build/1224/job/uw5oi1u34m8oped8#L244
- ...
> Fix missing version check on unpack test

- composer.json
This PR:
Without it tests won't pass:
```
Class ZipArchive was not found
```
> Add missing required-dev zip extension

- composer.json
- src/Analyser/Scope.php
- src/Reflection/Php/PhpFunctionFromParserNodeReflection.php
- src/Rules/Classes/UnusedConstructorParametersRule.php
- src/Rules/FunctionDefinitionCheck.php
- src/Rules/PhpDoc/IncompatiblePhpDocTypeRule.php
- src/Type/Php/ArrayFilterFunctionReturnTypeReturnTypeExtension.php
After `nikic/php-parser` release 4.0.2 we have issue on code that is not correctly checked, this should fix it.
The issue is generated from https://github.com/nikic/PHP-Parser/compare/v4.0.1...v4.0.2#diff-4abbd24bd532741591878bd14be6dd5dR15 where `$var` can be also an error.
> fix issues in phpstan level 7 generated from php-parser 4.0.2

- README.md
Hi,
Today i tried to create a custom error formatter but following the instructions lead to some errors thrown by Nette.
I figured it out so I thought it could help to clarify this on the readme.
It's not much I know but maybe I will contribute the error formatter itself later
> Clarify instructions for custom error formatter

- src/Type/Php/ArrayFilterFunctionReturnTypeReturnTypeExtension.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
- tests/PHPStan/Analyser/data/array-functions.php
Hi,
When `array_filter` is called without second argument, all non-truthy values are filtered. This patch adds support for this for both constant and other types (`NullType`)
> Add support for non-truthy values filtering with array_filter

- tests/PHPStan/Command/ErrorFormatter/CheckstyleErrorFormatterTest.php
- tests/PHPStan/Command/ErrorFormatter/JsonErrorFormatterTest.php
- tests/PHPStan/Command/ErrorFormatter/RawErrorFormatterTest.php
- tests/PHPStan/Command/ErrorFormatter/TableErrorFormatterTest.php
- tests/PHPStan/Command/ErrorFormatter/TestBaseFormatter.php
Hi @ondrejmirtes as indicate in https://github.com/phpstan/phpstan/pull/552#issuecomment-386999834 some refactor on error formatter tests.
1. Create an abstract class used to:
- generate some "standard" analysis result (no error, 1 file error, q generic error, multiple mixed errors, ...)
- centralise format output extraction
2. Create specific test case for each formatter for each type of expected output
**NB**: I found that JSON formatter strip path if pretty format is included, otherwise report full path. IMHO this is a bug (pretty is used for formatting, not for change the generate output), so I remove it (see https://github.com/phpstan/phpstan/commit/1c1e31d4682bb251784171c0643e3ec8f90abb92), but this should be a BC in the output, if you agree I'll create a new PR that split format to …
> Refactor formatter tests

- src/Command/AnalyseCommand.php
Currently `exclude_analyse` works only on analyse step in phpstan, but error can occurs on robot-loader's parse step, when you have same classes in tests.
> Add `exclude_analyse` support for RobotLoader

- src/Type/Php/ReplaceFunctionsDynamicReturnTypeExtension.php
We can recognize return type of `substr_replace` function, based on #1 parameter `string`.
http://php.net/manual/en/function.substr-replace.php
> substr_replace return type extension

- conf/config.neon
- src/Analyser/Scope.php
- src/Testing/TestCase.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
- tests/PHPStan/Analyser/data/dynamic-constant.php
Hi.
I added feature called "dynamic constants".
It is good when you use constants for configuration like for example WordPress [https://github.com/WordPress/WordPress/blob/6fd8080e7ee7599b36d4528f72a8ced612130b8c/wp-config-sample.php] does.
You only need to configure which constants are dynamic, type of constant is resolved from their definition.
Limitation: This feature is not designed to cover union types.
Possible BC break: Some constants where hardcoded with its type in phpstan's core (see Scope.php diff from line 843). They were moved to dynamic constants configuration and the type is now resolved from value which may differ from previous type.
Example configuration in your phpstan.neon
```yaml
parameters:
dynamicConstantNames:
- MyNamespace\MyClass::MY_DYNAMIC_CONSTANT
- …
```
> Configuration of dynamic constants

- bin/phpstan
- src/Command/AnalyseCommand.php
This should make for some nicer looking fatal errors and uncatched exceptions. The `--debug` option still remains.
> Better application exceptions

- build/phpstan.neon
- conf/config.neon
- src/Command/AnalyseCommand.php
- src/DependencyInjection/ContainerFactory.php
The `$container->initialize();` line is there so that extensions can use their own `CompilerExtension`s with `afterCompile` method.
Notice the line `Using Symfony container...`.
> Console output as a service

- src/Analyser/Scope.php
- src/Analyser/TypeSpecifier.php
- src/Analyser/TypeSpecifierContext.php
- src/Broker/Broker.php
- src/Reflection/Php/PhpMethodReflection.php
- src/Reflection/Php/PhpParameterFromParserNodeReflection.php
- src/Reflection/Php/PhpParameterReflection.php
- src/Testing/RuleTestCase.php
- src/Testing/TestCase.php
Removes an always-true predicate and an always-false one, and adds `null` to a few property types that weren't listed as nullable.
> Fix issues found by Psalm

- src/Reflection/SignatureMap/functionMap.php
Both filename and quality parameters are optional.
Fixes #1213.
> Update imagewbp()'s function map

- src/Type/Php/ReplaceFunctionsDynamicReturnTypeExtension.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
- tests/PHPStan/Analyser/data/replaceFunctions.php
Fixes #1217 
I copied the `str_replace` related tests for `str_ireplace` then confirmed that a test failed:
```
1) PHPStan\Analyser\NodeScopeResolverTest::testReplaceFunctions with data set #13 ('string', 'str_ireplace('.', ':', $intOr...ngKey)')
str_ireplace('.', ':', $intOrStringKey) at die
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'string'
+'array<string>|string'
```
Then added `str_ireplace` to `src/Type/Php/ReplaceFunctionsDynamicReturnTypeExtension.php` and confirmed that the failing test passed.
> Adding str_ireplace to Dynamic Return Type Extension

- README.md
> Readme: use ParametersAcceptorSelector to get return type for method

- src/Reflection/SignatureMap/functionMap.php
In documentation ( http://php.net/manual/en/function.key.php ) is `If the internal pointer points beyond the end of the elements list or the array is empty, key() returns NULL.` So I fixed return type from `false` to `null`.
> Fix key() method stub

- src/Reflection/SignatureMap/functionMap.php
Some options (such as [IP_MULTICAST_IF](http://php.net/manual/en/function.socket-get-option.php)) accept a string argument, so this PR extends the 4th argument of `socket_set_option()` to allow that
> Correct the 4th argument to socket_set_option()

- build.xml
- composer.json
This PR
Follows https://github.com/phpstan/phpstan/pull/1256#issuecomment-406736436.
> Enhancement: Run composer normalize during build

- build.xml
This PR
Follows https://github.com/phpstan/phpstan/pull/1258#discussion_r204221133.
> Enhancement: Use --ansi option when running Symfony console commands

- build.xml
- tests/phpunit.xml
This PR
💁‍♂️ This way the reference will always be up-to-date. Also see current `composer.json`: https://github.com/phpstan/phpstan/blob/bfd31f1bb31b855f47c271f61d7e67cb5f054870/composer.json#L35.
For reference, see https://www.phing.info/phing/guide/en/output/chunkhtml/XmlLintTask.html.
> Enhancement: Reference phpunit.xsd as installed with composer

- build.xml
This PR
💁‍♂️ Give me a moment to find out how one can pass `--colors=always` through to `phpunit` (when running with `brianium/paratest`.
> Enhancement: Use colors

- .travis.yml
This PR
💁‍♂️ Note that Travis updates `composer` already, see
* https://travis-ci.org/phpstan/phpstan/jobs/406684332#L438
* https://travis-ci.org/phpstan/phpstan/jobs/406684332#L468
> Fix: Update composer itself once only

- .travis.yml
- appveyor.yml
This PR
Related to https://github.com/localheinz/composer-normalize/issues/68#issuecomment-410437851.
Follows https://github.com/composer/composer/issues/7516#issuecomment-410459001.
💁‍♂️ This is a temporary patch until `1.7.1` is released.
> Fix: Update composer itself to latest snapshot

- .travis.yml
- appveyor.yml
This PR
Follows #1331.
💁‍♂️ For reference, see https://github.com/composer/composer/compare/1.7.0...1.7.1.
> Fix: Use latest version of composer again

- src/PhpDoc/TypeNodeResolver.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
- tests/PHPStan/Analyser/data/var-annotations.php
Add initial support for stuff like
~~~php
/**
* @param callable(int $x, string ...$y): void $a
* @param Closure(int $x, string ...$y): void $b
*/
~~~
parameter and return types are currently ignored for `CallableType` which does not support them
> TypeNodeResolver: implement basic CallableTypeNode resolution

- tests/PHPStan/Reflection/data/function-definitions.php
closes #1360
This definition isn't compatible with [the function itself](http://php.net/ibase_wait_event), but apparently it was never a problem. :smiley:
> Tests compatibility with ext/interbase

- src/Reflection/SignatureMap/functionMap.php
According to [documentation](https://secure.php.net/xmlreader.expand), `XMLReader::expand()` method takes an optional `DOMNode` argument.
Test case : https://phpstan.org/r/4acbc01009a8562bb9a963daa6675985
> Fix XMLReader::expand() signature

- src/Reflection/SignatureMap/functionMap.php
Modifies readfile to recognize a return value of false, as [documented](https://secure.php.net/readfile#refsect1-function.readfile-returnvalues)
> readfile can return false

- src/Reflection/SignatureMap/functionMap.php
I'm not sure about other 'offsetExists' input params, return types seem ok to me (bool). The return values in `Yaf_` methods are totally unclear to me and PHP docs are also unclear, so I prefer to not touch them.
> Change return type ArrayIterator::offsetExists from void to bool (closes #1415)

- src/Reflection/SignatureMap/functionMap.php
`offsetGet` returns `mixed`, which makes me believe `offsetSet` should also take `mixed` and not just `string`. Seems also wrong in PHP docs.
> Adjust return type of ArrayIterator::offsetSet to mixed, not just string

- src/Reflection/PhpDefect/PhpDefectClassReflectionExtension.php
- tests/PHPStan/Reflection/PhpDefect/PhpDefectClassReflectionExtensionTest.php
- tests/PHPStan/Reflection/PhpDefect/data/DatePeriodChild.php
This teaches PHPStan about the properties on the `DatePeriod` class which are missing from reflection.
Is it an issue that these properties were not added until PHP 5.3.27/5.4.17?
http://php.net/manual/en/class.dateperiod.php#dateperiod.props
https://phpstan.org/r/2ad0f4a7e81cf4d2c1024733bf251aea
> Add properties for DatePeriod class

- src/Type/Php/VarExportFunctionDynamicReturnTypeExtension.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
Fixes #1457 
I more or less copied the implementation of `var_export` based on suggestion from @ondrejmirtes.
I did have to explicitly use the `ConstantBooleanType(true)` type instead of the `BooleanType` as the fallback for `print_r` because it doesn't ever return `false` (according to PHP's docs, if I call `print_r` with no parameters it does return `false` but also emits a Warning. Should I modify this PR to support that? I noticed `var_export` has a no parameter test, in which case it is marked as returning `string|null`. `var_export` when called with no parameters returns `null` and also emits a Warning).
> Adding support for second parameter of print_r (returns string when true)

- src/Reflection/SignatureMap/functionMap.php
See http://php.net/dns_check_record .
As `dns_check_record()` is just an alias of `checkdnsrr()` they obviously have the same signature. `checkdnsrr()` was correct, I fixed `dns_check_record()`.
> Mark second parameter "type" of dns_check_record() as optional.

- src/Reflection/SignatureMap/functionMap.php
This PR fixes an incorrectly reported issue that happens when the function `session_create_id` is used without passing the `$prefix` parameter. PHPStan warns that it is required, but it's not.
(PR from issue #1495).
> Make optional the parameter  of the function session_create_id

- README.md
There is still some work to be done but it may be useful to someone.
> Add link to Yii2 phpstan extension

- composer.json
There's a [bug](https://github.com/symfony/symfony/issues/28666) in symfony/console 3.4.16 and 4.1.5 where the exit code is reported as success if it failed.
This obviously affects this tool in a major way rendering it useless in a CI environment, so this PR ensures this bug cannot be installed.
> Prevent using symfony/console with broken exit code handling

- src/Reflection/SignatureMap/functionMap.php
`openssl_csr_get_subject()` returns false on error:
```
>>> openssl_csr_get_subject('')
=> false
```
This updates the signature.
Thanks!
> openssl_csr_get_subject returns false on error

- src/Analyser/NodeScopeResolver.php
- src/PhpDoc/PhpDocBlock.php
- src/Reflection/Php/PhpClassReflectionExtension.php
- src/Reflection/Php/PhpMethodReflection.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
- tests/PHPStan/Analyser/data/inheritdoc-from-trait.php
- tests/PHPStan/Analyser/data/inheritdoc-from-trait2-definition.php
- tests/PHPStan/Analyser/data/inheritdoc-from-trait2-definition2.php
- tests/PHPStan/Analyser/data/inheritdoc-from-trait2.php
I'm not sure how to fix this one. The problem is that the [`$trait`](https://github.com/phpstan/phpstan/blob/ad0406193c72a5ea108e7d7be86b61e3269e8df6/src/Analyser/NodeScopeResolver.php#L1970) variable is never reset if the `@inheritdoc` comes from another source.
@ondrejmirtes Any ideas?
> @inheritdoc from trait

- src/Reflection/SignatureMap/functionMap.php
The 3rd and 4th parameters to [ldap_control_paged_result_response()](http://php.net/manual/en/function.ldap-control-paged-result-response.php) are optional.
> Optional parameters for ldap (fixes #1585)

- src/Type/Php/PathinfoFunctionDynamicReturnTypeExtension.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
Make 'extension' optional by returning a `UnionType` in `PathinfoFunctionDynamicReturnTypeExtension`.
Fixes #1630
> Array from `pathinfo` may or may not contain `extension` key

- tests/PHPStan/Dependency/DependencyDumperTest.php
Fixes issue with this test on Windows (AppVeyor).
> Normalize path in `DependencyDumperTest`

- conf/config.neon
- src/Parser/CachedParser.php
- tests/PHPStan/Parser/CachedParserTest.php
I have project with more than 5000 files and when I try to analyze it requires more than 3G memory.
I added limit for that cache and hope it will decrease memory usage for huge projects.
> Limit amount of cached files for parser

- src/Reflection/SignatureMap/functionMap.php
Param #3 of [`extract()`](https://secure.php.net/extract) accepts `null`
> Fixes signature of `extract`

- src/Reflection/SignatureMap/functionMap.php
See http://php.net/manual/en/mongodb-driver-writeconcern.construct.php and https://github.com/mongodb/mongo-php-driver/blob/29f00a91043ad94dc75960ce5511e9c2ff63ce46/src/MongoDB/WriteConcern.c#L38..L55 - the first argument is called `w` and accepts a string or integer. Any other options will throw an exception.
> Fix signature for MongoDB\Driver\WriteConcern::__construct

- composer.json
- src/Rules/FunctionCallParametersCheck.php
This will fix situation where method return `void` but it its overwritten in `DynamicMethodReturnTypeExtension`.
Example scenario:
```php
class Foo
{
public function doSomething(): void
{
}
}
```
Custom extension:
```php
final class SampleExtension implements DynamicMethodReturnTypeExtension
{
public function isMethodSupported(MethodReflection $methodReflection): bool
{
return true;
}
public function getTypeFromMethodCall(MethodReflection $methodReflection, MethodCall $methodCall, Scope $scope): Type
{
return new ObjectType(SomethingOtherThanVoid::class);
}
}
```
Without this fix, you will get error:
```
------ ---------------------------------------------------------------------------------- 
Line   BarSpec.php                                                                       
------ …
```
> Correctly resolve return type including DynamicMethodReturnTypeExtension

- src/Reflection/SignatureMap/functionMap.php
[shmop_open()](http://php.net/manual/en/function.shmop-open.php) returns false in the event of an error.
> Add the failure return type for shmop_open()

- src/Reflection/SignatureMap/functionMap.php
Parameter #1 of `oci_set_db_operation` is of type "resource" according to documentation.
See http://php.net/manual/en/function.oci-set-db-operation.php
> Updating oci_set_db_operation signature

- src/Reflection/SignatureMap/functionMap.php
[PHP Documentation](http://php.net/manual/en/function.jddayofweek.php)
> Fix signature for jddayofweek - 2nd parameter is optional

- src/Reflection/SignatureMap/functionMap.php
> Correctly mark MultipleIterator constructor argument as optional

- src/Analyser/Analyser.php
- src/Rules/FileRuleError.php
- src/Rules/RuleErrorBuilder.php
- src/Rules/RuleErrors/RuleErrorWithMessageAndFile.php
- src/Rules/RuleErrors/RuleErrorWithMessageAndLineAndFile.php
- tests/PHPStan/Rules/RuleErrorBuilderTest.php
Adding more interfaces like this could lead to a combinatorial explosion, I know, but at least these three properties (message, line, file) should be covered. Plus I need it in my project.. 😊
Other option would be to maybe change the `PHPStan\Analyser\Error` interface and pass the `RuleError` in it, and let error formatter do all the work instead of the analyser. But that is a much bigger task that I didn't want to start without further discussion.
> Added possibility to override rule error file

- src/PhpDoc/PhpDocBlock.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
- tests/PHPStan/Analyser/data/method-phpDocs-inheritdoc.php
- tests/PHPStan/Analyser/data/methodPhpDocs-defined2.php
- tests/PHPStan/Analyser/data/methodPhpDocs-implicitInheritance.php
- tests/PHPStan/Analyser/data/methodPhpDocs-recursiveTrait.php
- tests/PHPStan/Analyser/data/methodPhpDocs-trait.php
- tests/PHPStan/Analyser/data/methodPhpDocs.php
Here's the second PR for #1828.
> Only inherit phpDoc comments of non-private methods

- src/Reflection/SignatureMap/functionMap.php
I came into issue where phpstan was throwing error on my `UTCDateTime` object since I initialized it with `DateTimeImmutable` object while this is perfectly acceptable according to the [documentation](https://secure.php.net/manual/en/class.mongodb-bson-utcdatetime.php) . This is possible fix, if not accepted please fix this issue or tell me how I should enhance this (as I'm very new here), and thanks!
> Update UTCDateTime construct hinting

- src/Reflection/SignatureMap/functionMap.php
Hi,
SplFileObject::current() can return false if the pointer is out of bounds.
This is not mentionned in the php.net website, but here's a reproducible code:
https://3v4l.org/6XefC
Thanks
> SplFileObject::current() can return false

- src/Reflection/PhpDefect/PhpDefectClassReflectionExtension.php
- src/Testing/TestCase.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
- tests/PHPStan/Analyser/data/properties-defined.php
- tests/PHPStan/Analyser/data/properties.php
Hopefully now the correct fix for #1537.
The replicates https://github.com/phpstan/phpstan/commit/a7421ce953ea8b78f8c955dbcd5d7237b214fc47 in  `PhpDefectClassReflectionExtension`.
(Applies to 0.10 too, is that receiving bug fixes?)
> Allow annotations to override properties set in PhpDefectClassReflectionExtension

- src/Reflection/SignatureMap/functionMap.php
> #1974 allow first parameter of DOMDocument::saveXML to be null

- src/Reflection/SignatureMap/functionMap.php
See http://php.net/posix_getpgid
> Returns the process group identifier of the process pid or FALSE on failure.
> posix_getpgid can return false

- src/Reflection/SignatureMap/functionMap.php
Adds the missing `$options` parameter to `MongoDB\Driver\ReadPreference::__construct` signature.
This parameter has existed since 1.2.0 version of the extension, see: https://www.php.net/manual/en/mongodb-driver-readpreference.construct.php
> Add missing parameter to MongoDB ReadPreference

- src/Rules/PhpDoc/InvalidThrowsPhpDocValueRule.php
- tests/PHPStan/Rules/PhpDoc/InvalidThrowsPhpDocValueRuleTest.php
- tests/PHPStan/Rules/PhpDoc/data/incompatible-throws.php
Sometimes I need to say my method is throwing nothing (`@throws void`). Because of since v0.11.x phpDoc is inherited from the parent if phpDoc is not present, there is no way how to say my implementation is not throwing anything.
Example (https://phpstan.org/r/65a8eada-13c9-4f91-a53e-4405dc695acb):
```php
<?php declare(strict_types = 1);
interface Foo
{
/**
* @throws \RuntimeException
*/
public function sayHello(string $message): void;
}
class Bar implements Foo
{
public function sayHello(string $message): void
{
echo $message;
}
}
class Baz implements Foo
{
/**
* @throws void
*/
public function sayHello(string $message): void
{
echo $message;
}
}
``` 
```
+----------------------------------------------------------------------+
| Line | test.php …
```
> InvalidThrowsPhpDocValueRule: allow `@throws void` phpDoc

- src/Command/AnalyseApplication.php
- src/Command/CommandHelper.php
PHP 7.1 supports pntl_async_signals where you no longer need to call pcntl_signal_dispatch every loop in order to trigger the signal handler.
This means when the user aborts via Ctrl+C or similar PHPStan will now exit immediately, rather than continue to run in the background.
This will resolve #1979
> Use pntl_async_signals

- src/Type/Php/ArrayFillFunctionReturnTypeExtension.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
Attempt to fix issue #1275 
Still learning the project so no idea if this is a decent workaround.
The original issue is caused by PHPStan getting stuck building a ConstantArrayType with all the items generated by the analysed array_fill.
This fix provides a fallback to the generic ArrayType if the array size is larger than (the magic number) 100.
> Fix array_fill analysis performance

- src/Reflection/PhpDefect/PhpDefectClassReflectionExtension.php
- tests/PHPStan/Reflection/PhpDefect/PhpDefectClassReflectionExtensionTest.php
By default `documentElement` is null when creating a new `DOMDocument`. See https://3v4l.org/HXsGV.
> documentElement can be null

- src/Reflection/SignatureMap/functionMap.php
As both the documentation and the [source code](https://github.com/phpredis/phpredis/blob/60223762ada628c26cb82386bed281e4ec097f4f/redis.c#L1001-L1009) say
> Document Redis::close returns bool

- src/Analyser/Scope.php
- tests/PHPStan/Analyser/ScopeTest.php
- tests/PHPStan/Analyser/data/compiler-halt-offset.php
`Scope::resolveType()` may fetch constants while trying to resolve their type. When the constant is `__COMPILER_HALT_OFFSET__`, if fails with the following error:
PHP Warning:  constant(): Couldn't find constant __COMPILER_HALT_OFFSET__
Currently, `Scope::resolveType()` has a special case for a few constants. I've added a new special case for `__COMPILER_HALT_OFFSET__`.
> Fix "Couldn't find constant __COMPILER_HALT_OFFSET__"

- .travis.yml
At the time of creating this PR, in Travis we have:
|TAG|PHP -v|
|-|-|
|`master`|8.0.0-dev|
|`7.4snapshot`|7.4.0-dev|
Ref: https://twitter.com/nikita_ppv/status/1094897743594770433
I think we can safely ignore PHP 8 for now, and instead check PHP 7.4 build results.
> Travis: build against 7.4snapshot instead of master

- README.md
:eyes: 
As asked in https://github.com/bitwombat/phpstan-zend-framework/issues/3, previous developers that have done similar efforts allowed me to mark this as the latest one among unofficial but supported Zend PHPStan extension.
I'm asking here to link it in the README to help the extension spread in both usage and support
> README.md: link Zend Framework extension

- src/Testing/LevelsTestCase.php
When building on systems with multiple php binaries, `exec('php -v');` takes the user/system default binary alias instead of the one that runs the command.
Using `PHP_BINARY` ensure that tests run with the same php binary and version.
> exec(): use PHP_BINARY instead of env php

- build.xml
- conf/config.neon
- src/Analyser/Scope.php
- src/Broker/Broker.php
- src/PhpDoc/ConstExprNodeResolver.php
- src/PhpDoc/PhpDocNodeResolver.php
- src/PhpDoc/Tag/MethodTagParameter.php
- src/PhpDoc/TypeNodeResolver.php
- src/Reflection/Annotations/AnnotationsMethodParameterReflection.php
- src/Reflection/Annotations/AnnotationsMethodsClassReflectionExtension.php
- src/Reflection/GenericParametersAcceptorResolver.php
- src/Reflection/Native/NativeParameterReflection.php
- src/Reflection/ParameterReflection.php
- src/Reflection/ParametersAcceptorSelector.php
- src/Reflection/Php/DummyParameter.php
- src/Reflection/Php/PhpClassReflectionExtension.php
- src/Reflection/Php/PhpFunctionFromParserNodeReflection.php
- src/Reflection/Php/PhpMethodFromParserNodeReflection.php
- src/Reflection/Php/PhpParameterFromParserNodeReflection.php
- src/Reflection/Php/PhpParameterReflection.php
- src/Rules/Functions/ReturnTypeRule.php
- src/Type/CallableType.php
- src/Type/ClosureType.php
- src/Type/ConstantTypeHelper.php
- tests/PHPStan/Reflection/GenericParametersAcceptorResolverTest.php
- tests/PHPStan/Reflection/ParametersAcceptorSelectorTest.php
- tests/PHPStan/Type/CallableTypeTest.php
This PR changes `ParametersAcceptorSelector` such that generics handling is transparent in most code that care about types in a function signature.
- Exposes parameter default values in Reflection (`ParameterReflection::getDefaultValue()`; this is needed during template type inference when some optional parameters are omitted)
- Adds `GenericParametersAcceptorResolver::resolve()`, a method that infers the template types of a `ParametersAcceptor` based on received arguments, and returns a fully resolved `ParametersAcceptor` (with template types replaced by standin types).
- Changes `ParametersAcceptorSelector::selectFromArgs()` / `ParametersAcceptorSelector::selectFromTypes()` to resolve the chosen `ParametersAcceptor`.
- Adds `ParametersAcceptorSelector::selectArguments()`, a method that …
> Template type handling in parameters acceptors 

- build.xml
- src/Type/TypeTraverser.php
I didn't notice at first, but the TypeTraverser introduced in #2177 leaks a lot of memory because it creates a reference cycle.
Here I remove the reference cycle. As a result, the increased memory limit in build.xml is not needed anymore. Time/CPU-wise, the change has no noticeable impact.
Caveat: I had to make the methods public. I'm not very happy with this, but this is the best solution I found.
> TypeTraverser: Avoid creating a reference cycle

- src/Analyser/NameScope.php
- src/Reflection/GenericParametersAcceptorResolver.php
- src/Type/CallableType.php
- src/Type/Generic/TemplateMixedType.php
- src/Type/Generic/TemplateObjectType.php
- src/Type/Generic/TemplateTypeMap.php
- src/Type/IntersectionType.php
- src/Type/Traits/NonGenericTypeTrait.php
- src/Type/UnionType.php
I'm adding a `::createXxx()` static constructor in this class in an other PR, so it makes sense to rename the existing `::empty()` to `::createEmpty()`. It's also more consistent with the rest of the code base.
> Rename TemplateTypeMap::empty() to ::createEmpty() for consistency

- src/Type/IterableType.php
- tests/PHPStan/Type/IterableTypeTest.php
Note: This PR depends on https://github.com/phpstan/phpstan/pull/2241.
This adds support for type inference on the iterable type:
``` php
<?php
/**
* @template K
* @template V
* @param iterable<K, V> $it
* @return array<K, V>
*/
function f($it) {
$ret = [];
foreach ($it as $k => $v) {
$ret[$k] = $v;
}
return $ret;
}
f(new ArrayIterator([1, 2, 3])); // array<int>
```
> Support template type inference on iterables

- src/Type/ArrayType.php
- src/Type/IntersectionType.php
- src/Type/UnionType.php
- tests/PHPStan/Analyser/data/generics.php
- tests/PHPStan/Type/ArrayTypeTest.php
Instead of passing a NeverType down the inner types when the received type is not compatible, we just skip. This simplifies inference a little.
Also, in unions and intersections, we can always let the inner type handle the received type.
This has the effect of allowing this to pass:
``` php
<?php
/**
* @template T
* @param array<\DateTime|array<T>> $a
* @return T
*/
function e($a) {
throw new \Exception();
}
/**
* @param int $int
*/
function testE($int) {
assertType('int', e([[$int]]));
}
```
> Small simplification on type inference

- src/Type/IterableType.php
- tests/PHPStan/Type/IterableTypeTest.php
Changes `IterableType::describe()` such that `IterableType(TemplateType(K), TemplateType(V))` is described as `iterable<K, V>` rather than `iterable`.
> Improve IterableType::describe() with template types

- src/Type/Constant/ConstantArrayType.php
- tests/PHPStan/Analyser/data/generics.php
- tests/PHPStan/Type/Constant/ConstantArrayTypeTest.php
This adds support for type inference on constant arrays: 
``` php
<?php
/**
* @template T
* @param array{foo: T, bar: int} $a
* @return T
*/
function f(array $a) {
return $a['foo'];
}
f(["foo" => "hello", "bar" => 1]); // string
```
> Support template type inference on constant arrays

- src/Rules/Classes/InstantiationRule.php
- src/Rules/FunctionCallParametersCheck.php
- src/Rules/Functions/CallCallablesRule.php
- src/Rules/Functions/CallToFunctionParametersRule.php
- src/Rules/Methods/CallMethodsRule.php
- src/Rules/Methods/CallStaticMethodsRule.php
- src/Type/Generic/TemplateTypeHelper.php
- tests/PHPStan/Generics/data/functions-5.json
- tests/PHPStan/Reflection/GenericParametersAcceptorResolverTest.php
- tests/PHPStan/Rules/Functions/CallToFunctionParametersRuleTest.php
- tests/PHPStan/Rules/Functions/data/call-generic-function.php
This changes `FunctionCallParametersCheck` to check that template types were successfully inferred in function calls.
``` php
<?php
/**
* @template A
* @param int|array<A> $a
*/
function f($a): void {
}
function test(): void {
f(1); // Unable to resolve the template type A in call to function f
}
```
> Check template type inference failures

- conf/config.level2.neon
- conf/config.neon
- src/Rules/Functions/TemplateTypeDeclarationRule.php
- src/Rules/Methods/TemplateTypeDeclarationRule.php
- src/Rules/TemplateTypeCheck.php
- src/Type/Generic/TemplateTypeFactory.php
- tests/PHPStan/Generics/TemplateTypeFactoryTest.php
- tests/PHPStan/Rules/Functions/TemplateTypeDeclarationRuleTest.php
- tests/PHPStan/Rules/Functions/data/template-type-bounds.php
- tests/PHPStan/Rules/Methods/TemplateTypeDeclarationRuleTest.php
- tests/PHPStan/Rules/Methods/data/template-type-bounds.php
Adds a rule to check the bound in `@template` annotations:
```
@template T of Foo // OK
@template T of int // Type parameter T of function foo has invalid bound int (only class name bounds are supported currently).
```
> Add TemplateTypeDeclarationRule

- src/Type/TypeCombinator.php
- tests/PHPStan/Type/TypeCombinatorTest.php
When subtractable types are disabled, `T|null` is `null`.
This is caused by TypeCombinator checking that the type is a MixedType.
I added a special case, but a proper fix would be to not inherit MixedType/ObjectType in template types.
I changed `TypeCombinatorTest::testUnion()` to test with subtractable types enabled and disabled.
> Fix union() when subtractable types are enabled

- src/Rules/PhpDoc/IncompatiblePhpDocTypeRule.php
- src/Type/Generic/TemplateTypeHelper.php
- src/Type/TypehintHelper.php
- tests/PHPStan/Analyser/data/generics.php
- tests/PHPStan/Rules/PhpDoc/IncompatiblePhpDocTypeRuleTest.php
- tests/PHPStan/Rules/PhpDoc/data/incompatible-types.php
There are two issues with template types when using native type hints:
- The IncompatiblePhpDocTypeRule rule will complain that the template type is not a super type of the type hint (because `(T of DateTime)->isSuperTypeOf(DateTime) is Maybe`)
- In the reflection of the function, the native type hint wins over the template type (for the same reasons). As a result, in the function body, template parameters have the type of their type hints
This PR fixes both issues.
> Allow native typehints with template types

- src/File/FileExcluder.php
- tests/PHPStan/File/FileExcluderTest.php
Fix copy-pasted from https://github.com/phpstan/phpstan/pull/1822
tests from https://github.com/phpstan/phpstan/issues/1821 (fixes #1821)
I also added test for magic wildcard without wildcard - excluding "/phpstan" also excludes "/phpstan-asdf".
> Fix path normalization of excludes_analyse rules

- src/Reflection/SignatureMap/functionMap.php
See https://github.com/phadej/igbinary/blob/a0316ffc8bab7e628c3679dac0ec6b78ded52f12/php_igbinary.h#L48 - the function always return `string` and not `?string`
> Fix igbinary_serialize() return type to string

- src/Reflection/SignatureMap/functionMap.php
The array returned from `stream_get_meta_data` at least _can_ contain the key `mediatype` containing the MIME type of a given base64 resource: https://3v4l.org/f094m
```php
<?php
$rh = fopen('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAGCAYAAAD68A/GAAAAAXNSR0IArs4c6QAAAAlwSFlzAAALEwAACxMBAJqcGAAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAAAQFJREFUCB0B9gAJ/w …
```
> Add missing array key `mediatype` to return of `stream_get_meta_data`

- src/Reflection/SignatureMap/functionMap.php
Signature for `disk_free_space` and `disk_total_space` do not match but the documentation is practically identical
* https://www.php.net/manual/en/function.disk-free-space.php
* https://www.php.net/manual/en/function.disk-total-space.php
> update disk_total_space signature

- src/Reflection/SignatureMap/functionMap.php
When parsing of the date/time fails for date_create_immutable_from_format
it will return false as a valid value. Although the php documentation does not
reflect this, it is demonstratable by visiting https://3v4l.org/etHCv.
> date_create_immutable_from_format also supports false

- src/Type/FileTypeMapper.php
- src/Type/Generic/TemplateMixedType.php
- src/Type/Generic/TemplateObjectType.php
- src/Type/Generic/TemplateTypeScope.php
- tests/PHPStan/Analyser/data/generics.php
- tests/PHPStan/Type/TypeCombinatorTest.php
This improves the logic of choosing whether a template type is resolvable (parameter strategy) or not (argument strategy). This also exposes the strategy in `TemplateType::describe(VerbosityLevel::precise())`.
Template types are resolvable when:
- Referenced in a param of the function where the template type was declared
- Referenced in a param of the method where the template type was declared
- Referenced in a param of a method of the class where the template type was declared
- Referenced in a property of the class where the template type was declared
Template types are not resolved when:
- Referenced in a `@var` annotation
- Inherited from an outter method, function, or class
- Used inside the method, function, or class that declared it
> Improve template type inheritance

- src/Reflection/SignatureMap/functionMap.php
As the title says, little change that allows passing `null` values to the first argument of the `ReflectionProperty::setValue` function
> Update the function signature of ReflectionProperty::setValue

- composer.json
Ran into an issue while working on https://github.com/maglnet/ComposerRequireChecker/pull/115 that the `build/PHPStan` directory doesn't exits on tagged releases because it's ignored on export https://github.com/phpstan/phpstan/blob/274726c0ba2a48a03608502ab309984f116fcbeb/.gitattributes#L1 
This PR proposes to move the PSR-4 autoloading of that directory to `require-dev` because it's obviously not meant for production.
> Move PSR-4 to build/PHPStan to require-dev

- composer.json
Exactly the same as #2347 but didn't realise until `0.11.15` was released.
> Move PSR-4 to build/PHPStan to require-dev (0.11.x)

- src/Analyser/Scope.php
- src/Analyser/TypeSpecifier.php
- tests/PHPStan/Analyser/TypeSpecifierTest.php
Fix https://github.com/phpstan/phpstan/issues/2356
This also fixes wrong XOR short circuiting (XOR always requires both operands to be evaluated)
> Fix #2356 (true is assumed to be always truthy)

- src/Reflection/SignatureMap/functionMap.php
Redis official docs indicates that exists return integer 0 or 1:
https://redis.io/commands/exists
Also in the library (most recent version, and even from 4.0 till now) also it return 0 or 1 for the exists method.
https://github.com/phpredis/phpredis/tree/5.0.2#exists
Updated the functionMap to return the correct type. Cause I'm getting the following error:
Strict comparison using === between bool and 1 will always evaluate to false.
> Updating Redis::exists return type

- src/Reflection/SignatureMap/functionMap.php
It is possible to set global options with ldap_set_option by using null as the first parameter. This can be used (for example) to disable certificate validation when connecting:
```
\ldap_set_option(null, \LDAP_OPT_X_TLS_REQUIRE_CERT, \LDAP_OPT_X_TLS_NEVER);
```
This PR adds null as a possible type for this function.
> Allow setting of global options with ldap_set_option

- conf/config.neon
- src/Reflection/SignatureMap/functionMap.php
- src/Type/Php/Base64DecodeDynamicFunctionReturnTypeExtension.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
- tests/PHPStan/Analyser/data/functions.php
Closes #1365 
* Note that I didn't change the return type in the signature of `base64_decode` in the `functionMap.php` because its a safer default. Is that right?
> Adding Base64DecodeDynamicFunctionReturnTypeExtension

- src/Reflection/ClassReflection.php
- src/Type/Generic/GenericObjectType.php
- src/Type/Generic/TemplateTypeMap.php
- src/Type/ObjectType.php
- tests/PHPStan/Type/Generic/GenericObjectTypeTest.php
- tests/PHPStan/Type/Generic/data/generic-classes-a.php
- tests/PHPStan/Type/Generic/data/generic-classes-b.php
This implements `isSuperTypeOf()` / `accepts()` for `GenericObjecType`.
A GenericObjectType (A) accepts an ObjectType (B) if all these conditions are met:
- B is accepted by A, according to ObjectType::accept()
- B is a GenericObjectType
- B is of the exact same class, or B has a parent that is accepted by A
- A and B have the same number of type parameters (template types)
- A and B's type parameters equal each other
Otherwise, we fallback on `ObjectType::accept()`
> Generic object type acceptance

- src/Analyser/Scope.php
- src/Type/Generic/TemplateMixedType.php
- src/Type/Generic/TemplateObjectType.php
- tests/PHPStan/Analyser/data/generics.php
- tests/PHPStan/Reflection/GenericParametersAcceptorResolverTest.php
This adds support for generics when inferring the type of new expressions:
```
/**
* @template T
*/
class C {
/** @param T $a */
public function __construct($a) {
}
}
new C(new DateTime()) // C<DateTime>
```
> "new" expression generic type inference

- src/Analyser/NodeScopeResolver.php
- src/Reflection/Php/PhpClassReflectionExtension.php
- tests/PHPStan/Analyser/data/generics.php
- tests/PHPStan/Generics/data/classes-3.json
- tests/PHPStan/Generics/data/classes-5.json
- tests/PHPStan/Generics/data/classes.php
- tests/PHPStan/Generics/generics.neon
When we inherit a method doc block from a parent class, we use the return type from the doc block only if it is a sub type of the native return type.
We were doing this check _before_ resolving template types, so it was always false.
> Fix implicit return type from inherited doc block

- src/Type/Generic/GenericObjectType.php
- tests/PHPStan/Analyser/data/generics.php
- tests/PHPStan/Type/Generic/GenericObjectTypeTest.php
- tests/PHPStan/Type/Generic/data/generic-classes-a.php
This adds support for template type inference in the GenericObjectType:
```
/**
* @template Foo<T>
* @param T $f
* @return T
*/
function f($f) {
}
f(new Foo(1)); // int
f(new Foo(new DateTime()); // DateTime
```
> Support infering template types from generic type

- src/Type/Generic/TemplateMixedType.php
- src/Type/Generic/TemplateObjectType.php
- tests/PHPStan/Generics/data/functions.php
- tests/PHPStan/Rules/Methods/CallMethodsRuleTest.php
- tests/PHPStan/Type/Generic/GenericObjectTypeTest.php
- tests/PHPStan/Type/TemplateTypeTest.php
This makes sure that we can pass a `X of DateTimeInterface` to a `Y of DateTimeInterface`, and that `Y` is inferred to be a `X of DateTimeInterface`, as long as the bounds are compatible.
This also changes `TemplateType::inferTemplateTypes()` such that we return an empty `TemplateTypeMap` when we receive an invalid type. This allows Rules to detect which types was not successfully inferred. From the user PoV, types that fail to infer still default to their bound - this is done by `TemplateTypeHelper`.
> Allow template types to be inferred to a received template type with compatible bound

- src/Type/ClosureType.php
- src/Type/Generic/GenericObjectType.php
- src/Type/ObjectType.php
- src/Type/StaticType.php
- src/Type/TypeWithClassName.php
- tests/PHPStan/Type/Generic/GenericObjectTypeTest.php
This improves on https://github.com/phpstan/phpstan/pull/2473, by also looking at generic ancestors of the received type.
```
/** @template T */
interface A {
}
/** @implements A<DateTime> */
class B {
}
/**
* @template T
* @param A<T> $f
* @return T
*/
function f($f) {
}
f(new B()); // DateTime
```
> Infer from generic ancestor

- src/Reflection/SignatureMap/functionMap.php
`zRangeByScore` allows `'+inf'` and `'-inf'` as start and end parameters
> Correct Redis::zRangeByScore signature

- src/Type/Generic/TemplateTypeHelper.php
Currently, in resolveTemplateTypes(), while traversing the generic type, we also traverse the resolved types.
This causes infinite recursions (and seg faults) when the generic type is referenced in the template type map:
```
$type = TemplateTypeFactory::create($scope, 'T');
$map = new TemplateTypeMap([
'T' => TemplateTypeHelper::toArgument($type),
]);
```
> Don't traverse resolved type

- src/Reflection/ClassReflection.php
- src/Reflection/Php/PhpClassReflectionExtension.php
- tests/PHPStan/Analyser/data/generics.php
This fixes this: https://phpstan.org/r/970a09ce-f4d4-4300-b970-228f8f4ed050
We use the display name of a ClassReflection as a cache key, when caching method. However, it is possible ClassReflections with different template types have the same display name (when the template types are template types themselves, but from different scopes).
> Fix method caching with different template types of the same name

- src/Analyser/MutatingScope.php
- src/Analyser/TypeSpecifier.php
- src/Rules/Classes/ImpossibleInstanceOfRule.php
- tests/PHPStan/Analyser/NodeScopeResolverTest.php
- tests/PHPStan/Analyser/data/instanceof.php
- tests/PHPStan/Rules/Classes/ImpossibleInstanceOfRuleTest.php
- tests/PHPStan/Rules/Classes/data/impossible-instanceof.php
This adds support for `$a instanceof $b` where `$b` is an expression (especially a class-string<> or a constant string), in TypeSpecifier.
> Support instanceof $expression 

- composer.json
They are both exactly the same in this context.
Thus I recommend using a single semver version/usage here.
> Stick to conventional semver

- README.md
This PR
💁‍♂ For reference, see https://github.com/ergebnis/phpstan-rules/pull/157.
> Fix: Rename reference after move to @ergebnis

- README.md
Zend Framework moved to Laminas, and I moved my extension as well: https://getlaminas.org/blog/2019-12-31-out-with-the-old-in-with-the-new.html
> Mark Zend to Laminas transfer

- README.md
I struggled a lot getting started with PHPStan because I couldn't find a simple example of a "default" `phpstan.neon`.
I added one in the README (in the future I may look in a `phpstan init` command because I think that would be even better).
> Add an example of a simple phpstan.neon file in the README

- README.md
We wrote the following rules:
- checking for the presence of setters and getters for common entity fields
- getter naming conventions for boolean fields in predicate style (like `isField`, `hasField`)
- availability of `add*` and `remove*` methods for Doctrine ArrayCollection
> Add new third party rules

- website/src/user-guide/ignoring-errors.md
`count` has first appeared in 0.11.17.
This is another take, the previous PR was #2777
> Document `count` in `ignoreErrors` config

- website/src/writing-php-code/phpdocs-basics.md
See https://www.php-fig.org/psr/psr-12/#44-methods-and-functions
> Method and function names MUST NOT be declared with space after the method name.
> Fixing PSR-12

- website/src/writing-php-code/phpdocs-basics.md
Add documentation about the fact PHPStan can't distinguish between internal type and class name that conflict with an internal type, and example of resolution using FQN.
Please do not hesitate to edit some parts as my english is probably bad.
> Special cases of classes named after PHP types

- .github/ISSUE_TEMPLATE/Support_question.md
- .github/ISSUE_TEMPLATE/config.yml
Today, when a GitHub user opens the link https://github.com/phpstan/phpstan/issues/new/choose he has 5 choices:
- choose a "Bug report" issue template
- choose a "Feature request" issue template
- choose a "Function signature mismatch" issue template
- choose a "Support question" issue template
- view security policy
However there is no real "Support question" issue template. This is rather a message to redirect the github user to Discussions: the template is used as a way to carry this information.
According to https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser a configuration file enables the use of `contact_links` to _redirect_ users looking for help to some page. This PR …
> Add GitHub issue configuration file for support question redirect

- website/src/developing-extensions/core-concepts.md
Add a notice message about settings being cached and the need to refresh.
So far I clear the cache by deleting the `phpstan` folder inside `sys_get_temp_dir/phpstan` maybe there is a better solution?
> Add a notice message about settings being cached

- .github/workflows/docker-nightly.yml
- .github/workflows/docker-stable.yml
This is result (https://github.com/users/JanMikes/packages/container/package/phpstan):
To verify run:
```
docker pull ghcr.io/janmikes/phpstan
docker manifest inspect --verbose ghcr.io/janmikes/phpstan | grep architecture
```
You should see output:
```
"architecture": "amd64",
"architecture": "arm64",
```
> [Docker] Support for multi-arch Docker builds

- .github/workflows/docker-nightly.yml
- .github/workflows/docker-stable.yml
Added missing arguments for action that runs `docker buildx build` under the hood.
When testing, times went from 13s to avg 3s, it was very fast already before 😄 with multi-arch builds the speedup will be more notable as QEMU is quite slow.
> [Docker] Building Docker images in GHA now uses layers cache

- website/src/_layouts/_base.njk
- website/src/app.pcss
* Remove .h-screen and .overflow-y-auto, which constrain the main content area to be only the height of the browser window, which causes a secondary scroll bar that only scrolls that content. Now, the main content area flows as part of the entire page.
* Add styling to explicitly fix the nav header to the top, and increase the content area top margin to account for the nav header being taken out of the normal layout flow.
I'm not familiar with how Tailwinds is supposed to be used, so there may be a more "tailwindy" way of doing this. This should work, though. I've tested several pages in both Safari and Chrome, and it looks good. The spacing between the bottom of the nav bar and the top of the content is not _exactly_ the same as it was, but it's only a pixel or two off, so I doubt anyone …
> Fix double scroll bar causing navigation issues

- website/src/writing-php-code/phpdoc-types.md
As per https://phpstan.org/blog/phpstan-0-12-released#%E2%80%9Cclass-string%E2%80%9D-pseudotype the `class-string` type supports narrowing by class subtype too.
> Document the signature for class-string subtypes

- website/src/_posts/solving-phpstan-error-unsafe-usage-of-new-static.md
Minor grammatical fix where sentence mixed up plural and singular.
> Grammatical fix in documentation for "Unsafe usage of new static()"

- website/src/config-reference.md
the described behaviour is the one I read in this code:
https://github.com/phpstan/phpstan-src/blob/89af4e7db257750cdee5d4259ad312941b6b25e8/src/Php/PhpVersionFactoryFactory.php#L37-L51
> infer php version from composer.json

- .github/workflows/integration-tests.yml
- e2e/integration/magento.neon
As discussed, I added the [phpstan-magento](https://github.com/bitExpert/phpstan-magento/) extension to the integration tests.
> Add magento extension to integration test workflow

- .github/workflows/integration-tests.yml
To make the CI of phpstan/phpstan-src#914 pass I had to open a PR in PHPUnit which was released in version `9.5.12`
> Bump the version of PHPUnit used in the integration tests

- .github/workflows/integration-tests.yml
To make the CI of phpstan/phpstan-src#914 pass I had to open a PR in the repository of Rector which got merged in commit [`303ecc3`](https://github.com/rectorphp/rector-src/commit/303ecc342da1484619c4f875ad67850feeb4b52b). Side note: this is not the latest commit on their `master` branch, but I didn't want to take the risk of bumping it to a more recent one
> Bump the version of Rector used in the integration tests

- website/src/user-guide/discovering-symbols.md
Typo fix: remove extra "a" term in "Create a file a that looks like this" ➤ "Create a file that looks"
> 🤏 Little typo fix

- website/src/developing-extensions/rules.md
Hi!
The previous paragraph mentions you should put your configurable rules under `services`. 
However some people (like me 😅) will just read the code example and won't understand why they face the following issue, because they are trying to put configurable rules under `rules`:
```
Invalid configuration:
The item 'rules › 142' expects to be string, array given.
```
Thanks!
> Clarify configurable rules definition documentation
