src/Command/AnalyseCommand.php

Alias analyze, default app to analyse command

---

src/Analyser/NodeScopeResolver.php
src/Analyser/Scope.php
src/Analyser/TypeSpecifier.php
src/Reflection/Php/PhpClassReflectionExtension.php
src/Reflection/Php/PhpMethodReflection.php
src/Reflection/Php/UniversalObjectCrateProperty.php
src/Type/ArrayType.php
src/Type/CallableType.php
src/Type/FalseBooleanType.php
src/Type/FileTypeMapper.php
src/Type/FloatType.php
src/Type/IterableIterableType.php
src/Type/JustNullableTypeTrait.php
src/Type/MixedType.php
src/Type/ObjectType.php
src/Type/TrueBooleanType.php
src/Type/TrueOrFalseBooleanType.php
src/Type/TypehintHelper.php
src/Type/UnionIterableType.php
src/Type/VoidType.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php

I think there is no difference between `mixed` and `mixed|null`.

MixedType is nullable by default

---

src/Rules/Functions/PrintfParametersRule.php
tests/PHPStan/Rules/Functions/PrintfParametersRuleTest.php
tests/PHPStan/Rules/Functions/data/printf.php

Support regex-like character classes for sscanf

---

bin/phpstan
conf/config.neon
src/Analyser/Analyser.php
src/Command/AnalyseApplication.php
src/Command/AnalyseCommand.php
src/FileHelper.php
tests/PHPStan/Analyser/AnalyserIntegrationTest.php
tests/PHPStan/Analyser/AnalyserTest.php
tests/PHPStan/Analyser/AnalyserTraitsIntegrationTest.php
tests/PHPStan/FileHelperTest.php
tests/PHPStan/Rules/AbstractRuleTest.php
tests/bootstrap.php

Fix for https://github.com/phpstan/phpstan/issues/73

Fixed excluding

---

src/Rules/Functions/PrintfParametersRule.php
tests/PHPStan/Rules/Functions/data/printf.php

Fix for https://github.com/phpstan/phpstan/issues/79.

Fixed printf/sprintf/sscanf/fscanf format parsing

---

src/Reflection/Annotations/AnnotationsPropertiesClassReflectionExtension.php

Refactor annotation properties extension. There is no need of Broker.

Refactor annotation properties extension, no need of Broker

---

src/Broker/ClassNotFoundException.php
src/Broker/FunctionNotFoundException.php
tests/PHPStan/Analyser/AnalyserIntegrationTest.php
tests/PHPStan/Broker/BrokerTest.php

Hello!
Just a simple wording fix in two exceptions.

Fix wording in *NotFoundExceptions

---

README.md
conf/config.neon
src/Command/AnalyseApplication.php
src/Command/AnalyseCommand.php

Adding the ability to configure PHPStan to read PHP files with non-standard file extensions
#123

Add support for custom php file extensions

---

src/Reflection/Annotations/AnnotationMethodReflection.php
src/Reflection/Annotations/AnnotationsMethodsClassReflectionExtension.php
src/Type/FileTypeMapper.php
tests/PHPStan/Reflection/Annotations/AnnotationsMethodsClassReflectionExtensionTest.php
tests/PHPStan/Reflection/Annotations/data/annotations-methods.php

Provides a failing test for `@method static ...`

Failing test

---

README.md

I had trouble discovering how to run tests. Having this would have helped me.

Help contributors discover how to run tests

---

conf/config.neon

Required for [phpstan-compiler](https://github.com/fprochazka/phpstan-compiler#phpstan-phar-compiler)

use detected temp dir for filestorage 

---

src/Command/AnalyseCommand.php

Hello,
I have something like this in my config file and I need expand %rootDir% var.
```
parameters:
tmpDir: %rootDir%/../../../temp/phpstan
```

Expand `tmpDir` config parameter

---

build.xml

Reflects 38b67b8d, file phpcs.xml is autodiscovered by phpcbf.

Fix build configuration for cs-fix target

---

src/Analyser/NodeScopeResolver.php
src/Analyser/Scope.php
src/Analyser/SpecifiedTypes.php
src/Analyser/TypeSpecifier.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Analyser/TypeSpecifierTest.php
tests/PHPStan/Analyser/data/type-elimination.php

TypeSpecifier: support simple variable filtering by truthy value

---

src/Reflection/Annotations/AnnotationsMethodsClassReflectionExtension.php
src/Type/FileTypeMapper.php
tests/PHPStan/Reflection/Annotations/AnnotationsMethodsClassReflectionExtensionTest.php
tests/PHPStan/Reflection/Annotations/data/annotations-methods.php

Based on https://github.com/phpstan/phpstan/pull/371

Fixes of parsing method annotations

---

src/Analyser/TypeSpecifier.php
tests/PHPStan/Analyser/TypeSpecifierTest.php

[closes #398]
https://phpstan.org/r/0bad21a82efd3ff3e2a75f78e1f8ec93

TypeSpecifier: support if (is_int($foo) === true)

---

src/Analyser/NodeScopeResolver.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Analyser/data/if.php

[closes #403]
https://phpstan.org/r/38d2ce36a3d7d2376e2e4c39e2fac7a0

Fixed appending value to null

---

src/Command/AnalyseCommand.php

I think this would be more usable for users.

New option --memory-limit

---

composer.json

Require jean85/pretty-package-versions ^1.0.2

---

src/Type/FloatType.php
tests/PHPStan/Type/FloatTypeTest.php

https://phpstan.org/r/6e6d2945d1000127c4909c05c7c87103

FloatType: fix accepting int|float

---

src/Reflection/FunctionReflection.php
tests/PHPStan/Rules/Functions/CallToFunctionParametersRuleTest.php
tests/PHPStan/Rules/Functions/data/call-to-weird-functions.php

Fixed incorrect argument number for mysqli_fetch_all

---

src/Reflection/PhpDefect/PhpDefectClassReflectionExtension.php
tests/PHPStan/Reflection/PhpDefect/PhpDefectClassReflectionExtensionTest.php

Fixes #526 
EDIT: Hmm :( I'll fix it..

Fixed undefined properties in libXMLError

---

.travis.yml

backported from phpstan/phpdoc-parser

travis: simplify build

---

README.md

Added Symfony to the list of unofficial extensions

---

src/Rules/Functions/CallToCountOnlyWithArrayOrCountableRule.php
tests/PHPStan/Rules/Functions/CallToCountOnlyWithArrayOrCountableRuleTest.php
tests/PHPStan/Rules/Functions/data/count.php

Fixes  #775.
If you have an idea for better wording, please suggest. 😉

CallToCountOnlyWithArrayOrCountableRule: Better message for non-countables

---

src/Command/AnalysisResult.php
tests/PHPStan/Command/AnalysisResultTest.php

Implements #838 
Replaces #839

#838 sort file-specific reports alphabetically and by line number

---

src/Reflection/SignatureMap/functionMap.php

stristr may return false

---

README.md

I am not good with writing text, so feel free to request changes or modify it in any way. :)

Documentation for Type-specifying extensions

---

src/Reflection/SignatureMap/functionMap.php

http://php.net/manual/en/function.ldap-search.php
```
Returns a search result identifier or FALSE on error.
```

ldap_search: returns resource|false

---

src/Rules/Properties/ReadingWriteOnlyPropertiesRule.php

If I find more during #952, I'll group them to open a single PR :smile:

Use Node\Expr when searching for reading/writing only properties

---

src/Command/ErrorFormatter/CheckstyleErrorFormatter.php
src/Command/ErrorFormatter/RelativePathHelper.php
src/Command/ErrorFormatter/TableErrorFormatter.php
tests/PHPStan/Command/ErrorFormatter/CheckstyleErrorFormatterTest.php
tests/PHPStan/Command/ErrorFormatter/TableErrorFormatterTest.php

refs #550: generate report with relative file path

---

src/Command/ErrorFormatter/CheckstyleErrorFormatter.php
tests/PHPStan/Command/ErrorFormatter/CheckstyleErrorFormatterTest.php

Closes #553 
* https://github.com/phpstan/phpstan/pull/554/commits/aa23c1b1f1c1e6f785b1e5414e7a1b6712c8ce41: refs #553: group errors per file in checkstyle formatter
This should be merged after #550 (need to rebase before merge)

refs #553: group errors in checkstyle formatter

---

src/Command/ErrorFormatter/RawErrorFormatter.php
tests/PHPStan/Command/ErrorFormatter/RawErrorFormatterTest.php

Add test for `RawErrorFormatter` class

refs #TECH: add tests for RawErrorFormatter

---

src/Rules/Properties/TypesAssignedToPropertiesRule.php
src/Rules/Properties/WritingToReadOnlyPropertiesRule.php

Use more stricter Nodes in rules

---

src/Command/AnalyseCommand.php

Refs #709 
Redirect warning/error messages that are not related to specified ErrorFormater to a stderror.
This is a PoC, need more work before consider it mergeable.

refs #709: redirect messages to stderror [WIP]

---

src/Testing/LevelsTestCase.php
src/Testing/TestCase.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Command/ErrorFormatter/TableErrorFormatterTest.php
tests/PHPStan/File/FileExcluderTest.php
tests/PHPStan/File/FileHelperTest.php
tests/PHPStan/Rules/Classes/InstantiationRuleTest.php
tests/PHPStan/Rules/Functions/CallCallablesRuleTest.php
tests/PHPStan/Rules/Properties/AccessPropertiesRuleTest.php
tests/PHPStan/Rules/Variables/ThisVariableRuleTest.php
tests/phpunit.xml

This is a continuation of #885

Fix Windows build

---

src/Reflection/SignatureMap/functionMap.php

SplFixedArray::__construct argument is optional

---

src/Reflection/SignatureMap/functionMap.php

fixes https://github.com/phpstan/phpstan/issues/1092

get_headers added optional context parameter

---

src/Analyser/NodeScopeResolver.php
src/Analyser/Scope.php
src/Broker/Broker.php
src/PhpDoc/PhpDocNodeResolver.php
src/PhpDoc/ResolvedPhpDocBlock.php
src/Reflection/ClassConstantReflection.php
src/Reflection/ClassReflection.php
src/Reflection/FinalizableReflection.php
src/Reflection/FunctionReflection.php
src/Reflection/FunctionReflectionFactory.php
src/Reflection/InternableReflection.php
src/Reflection/Native/NativeFunctionReflection.php
src/Reflection/Native/NativeMethodReflection.php
src/Reflection/Php/PhpClassReflectionExtension.php
src/Reflection/Php/PhpFunctionFromParserNodeReflection.php
src/Reflection/Php/PhpFunctionReflection.php
src/Reflection/Php/PhpMethodFromParserNodeReflection.php
src/Reflection/Php/PhpMethodReflection.php
src/Reflection/Php/PhpMethodReflectionFactory.php
src/Reflection/Php/PhpPropertyReflection.php
src/Testing/TestCase.php
src/Type/FileTypeMapper.php
tests/PHPStan/Reflection/Annotations/FinalAnnotationsTest.php
tests/PHPStan/Reflection/Annotations/InternalAnnotationsTest.php
tests/PHPStan/Reflection/Annotations/data/annotations-final.php
tests/PHPStan/Reflection/Annotations/data/annotations-internal.php

Things to note:
* I'm not very happy with the `InternableReflection` and `FinalizableReflection` names
* Any suggestions?
* The whole thing is quite repetitive
* I don't think adding something like a `Modifiers` class would make it any shorter
* `@final` is only supported for classes, functions and methods
I guess this is too early to merge? Are you planning on using branches more extensively in the future? It seems to work quite nicely in larger projects like Symfony to create release branches and then merge hotfixes upwards.

@final and @internal attributes

---

src/Reflection/SignatureMap/functionMap.php

https://secure.php.net/manual/en/splfileinfo.getrealpath.php

Fixed SplFileInfo::getRealPath() signature

---

phpcs.xml
src/Analyser/NodeScopeResolver.php
src/Analyser/Scope.php
src/Cache/MemoryCacheStorage.php
src/Command/ErrorFormatter/RawErrorFormatter.php
src/Reflection/Php/PhpFunctionFromParserNodeReflection.php
src/Reflection/Php/PhpFunctionReflection.php
src/Reflection/Php/PhpMethodReflection.php
src/Type/Constant/ConstantArrayType.php
src/Type/FileTypeMapper.php
src/Type/TypeCombinator.php

Together with PHPStorm and https://github.com/kalessil/phpinspectionsea, here are some improvements that we can make to PHPStan :smile:

Improvements

---

src/Type/Php/ArgumentBasedFunctionReturnTypeExtension.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php

add more array_ functions that return same type as first argument

---

src/Reflection/SignatureMap/functionMap.php

SplFileObject::fread can return false on failure

---

.travis.yml

Caching Composer makes tests run faster.

Faster Travis tests

---

src/Reflection/SignatureMap/functionMap.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php

preg_replace may return null

---

src/Reflection/SignatureMap/functionMap.php

http://php.net/hex2bin#refsect1-function.hex2bin-returnvalues

hex2bin may return false

---

src/Type/Php/ArraySearchFunctionDynamicReturnTypeExtension.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Analyser/data/array-functions.php

array_search return type extension fix when needle arg is variable

---

README.md

@ondrejmirtes Thank you for your work.

Announce Larastan in README

---

src/Reflection/SignatureMap/functionMap.php

Fix wrong signature of V8JS::__construct

---

.travis.yml

On php:master there's no xdebug

Support testing without installed xdebug

---

src/Reflection/SignatureMap/functionMap.php

Match PDO constructor argument signature

---

src/Reflection/SignatureMap/functionMap.php

time_nanosleep can return array|bool

Update time_nanosleep definition

---

build/phpstan.neon

Anchor ignored errors in self

---

src/Reflection/SignatureMap/functionMap.php

Update openssl_csr_sign signature

---

src/Reflection/PhpDefect/PhpDefectClassReflectionExtension.php

Adds properties for Directory class

---

src/Reflection/SignatureMap/functionMap.php

Generator::throw() should accept Throwable

---

src/Reflection/SignatureMap/functionMap.php

See documentation here: http://php.net/manual/en/function.curl-init.php

Fixing return type spec for curl_init.

---

src/Reflection/SignatureMap/functionMap.php

See specification: http://php.net/manual/en/function.hexdec.php

Adding changing return type of hexdec to int|float

---

conf/config.neon
src/Type/Php/CurlInitReturnTypeExtension.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php

Add type extension for curl_init with no parameters

---

src/Reflection/SignatureMap/functionMap.php

For reference: https://github.com/php/php-src/pull/2031#issuecomment-427581754

opcache_get_status can return false sometimes

---

src/Reflection/SignatureMap/functionMap.php

exif_imagetype() may return false. See http://php.net/manual/en/function.exif-imagetype.php

Fix return type of exif_imagetype()

---

composer.json

This PR
💁‍♂️ For reference, see https://github.com/localheinz/composer-normalize/compare/0.8.0...0.9.0.

Enhancement: Update localheinz/composer-normalize

---

src/Type/ResourceType.php
tests/PHPStan/Rules/Cast/InvalidCastRuleTest.php
tests/PHPStan/Rules/Cast/data/invalid-cast.php

This will enable phpstan to allow int cast of resources.

Add resource int cast

---

.travis.yml

Testing wether this actually works.

[WIP] Added PHAR build stage to Travis

---

README.md
src/Analyser/Analyser.php
src/Analyser/IgnoredError.php
tests/PHPStan/Analyser/AnalyserTest.php

Basically it's just tests fix for https://github.com/phpstan/phpstan/pull/1411

Scoped ignored messages by path

---

src/Analyser/Scope.php

Follow up of https://github.com/phpstan/phpstan/pull/1628#issuecomment-439930581

Use isSuperTypeOf instead of instanceof

---

appveyor.yml
build/ignore-windows-errors.neon
composer.json

Probably, it needs some extensions for AppVeyor builds.

Fix build on AppVeyor

---

src/Analyser/Scope.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Analyser/data/ternary.php

Fixes #1598, #1355, replaces #1402

Fix condition filtering in short ternary operator

---

src/Type/Php/ArrayFilterFunctionReturnTypeReturnTypeExtension.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php

See https://github.com/phpstan/phpstan/issues/1607

Fix: return type of array_filter($mixed)

---

conf/config.neon
src/Reflection/SignatureMap/functionMap.php
src/Type/Php/HrtimeFunctionReturnTypeExtension.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Analyser/data/php73_functions.php

See http://php.net/manual/en/function.hrtime.php

Hrtime support for PHP 7.3

---

src/Type/Php/MbFunctionsReturnTypeExtension.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Analyser/data/functions.php

Fix https://github.com/phpstan/phpstan/issues/1698

Support encoding aliases for mb_* functions

---

src/Reflection/SignatureMap/functionMap.php

http://php.net/manual/en/function.pg-field-type-oid.php

pg_field_type_oid returns int|false

---

src/Analyser/Scope.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Rules/Functions/CallToFunctionParametersRuleTest.php
tests/PHPStan/Rules/Functions/data/function-with-int-parameter-that-created-by-addition.php

Fix https://github.com/phpstan/phpstan/issues/1244

Fix failure to recognise initialize int type

---

src/Analyser/NodeScopeResolver.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Analyser/data/array-destructuring.php

Fix https://github.com/phpstan/phpstan/issues/1715

Fix array incorrectly inferred as string after using "list()"

---

src/Reflection/SignatureMap/functionMap.php

According to PHP documentation tmpfile [returns false on error](https://secure.php.net/manual/en/function.tmpfile.php#refsect1-function.tmpfile-returnvalues)

tmpfile returns false on error

---

src/Reflection/SignatureMap/functionMap.php

https://github.com/phpstan/phpstan-strict-rules/issues/49

Serializable::unserialize has parameter $serialized of type string

---

src/Rules/Methods/MethodSignatureRule.php
tests/PHPStan/Rules/Methods/data/method-signature-definition.php
tests/PHPStan/Rules/Methods/data/method-signature.php

Fix method signature rule for private methods

---

src/Reflection/SignatureMap/functionMap.php

PDOStatement::fetchColumn() may return NULL

---

src/Analyser/NodeScopeResolver.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Analyser/data/string-array-access.php
tests/PHPStan/Rules/Arrays/OffsetAccessAssignmentRuleTest.php
tests/PHPStan/Rules/Arrays/data/offset-access-assignment-to-scalar.php
tests/PHPStan/Rules/Methods/data/returnTypes.php

fixes https://github.com/phpstan/phpstan/issues/1875

Fixed array access on string

---

src/Type/ObjectType.php
tests/PHPStan/Rules/Arrays/data/nonexistent-offset.php

Subclasses of "extra offset classes" are offset accessible too

---

README.md

...to README.md. Cause they were missing.

Add doc about error formatters json and prettyJson

---

src/Reflection/SignatureMap/functionMap.php

Fix for issue [#1957](https://github.com/phpstan/phpstan/issues/1957)

Fix void return typehint for Ds\Set::first()

---

src/Reflection/SignatureMap/functionMap.php

Too bad this wasn't fixed in #1958.

Fix void return typehint for Ds\Set::last()

---

src/Type/Php/CountFunctionReturnTypeExtension.php
src/Type/Php/CountFunctionTypeSpecifyingExtension.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php

function count: Added support for 2nd parameter

---

README.md

Add Unofficial Drupal extensions

---

src/Reflection/SignatureMap/functionMap.php

Adding |false to return types of glob function

[#2036] glob can return false

---

src/Reflection/SignatureMap/functionMap.php

See: https://www.php.net/manual/en/domnamednodemap.count.php

Add DOMNamedNodeMap::count

---

src/Rules/Classes/InstantiationRule.php
tests/PHPStan/Rules/Classes/InstantiationRuleTest.php
tests/PHPStan/Rules/Classes/data/instantiation.php

https://phpstan.org/r/fc735c04-c34a-4bc5-bce3-09fb1571ad5b
Current behavior: no errors
New behavior: 
```  
11     Instantiated class UndefinedClass1 not found.
14     Instantiated class UndefinedClass2 not found.
21     Instantiated class UndefinedClass4 not found.
```

Extend instantiation rule

---

build/composer-require-checker.json
build/phpstan.neon
src/Command/CommandHelper.php

See https://github.com/phpstan/extension-installer

Extension installer: support automatic inclusion of extension config files

---

phpcs.xml
src/Analyser/SpecifiedTypes.php
src/PhpDoc/ResolvedPhpDocBlock.php
src/Reflection/SignatureMap/ParameterSignature.php
src/Rules/Operators/InvalidComparisonOperationRule.php
tests/PHPStan/Type/CallableTypeTest.php
tests/PHPStan/Type/Constant/ConstantArrayTypeTest.php
tests/PHPStan/Type/Constant/ConstantIntegerTypeTest.php
tests/PHPStan/Type/IntegerTypeTest.php

TODO: Write motivations and finish custom rules.

Add a rule to enforce one line only between functions declarations

---

src/Reflection/SignatureMap/functionMap.php

Ref: https://github.com/php/php-src/blob/php-7.3.2/ext/imap/php_imap.c#L4751

Update imap_thread signature to return false

---

src/Reflection/SignatureMap/functionMap.php

Fix sodium_crypto_scalarmult_base signature

---

README.md

Hi, I think it could be useful to mention the unofficial userland extensions of this amazing tool.
I've listed only the extensions I know, feel free to choose only the one you consider valid.

README.md: list third-party rules

---

README.md

Following https://github.com/phpstan/phpstan/pull/2130

README: add pepakriz/phpstan-exception-rules

---

src/Reflection/SignatureMap/functionMap.php

As per [the documentation](https://php.net/bcscale) and [the source code](https://github.com/php/php-src/blob/37d01ff81a6b/ext/bcmath/bcmath.c#L565).

Fix bcscale method signature

---

.github/FUNDING.yml

Need to escape the / for php package names

Update tidelift link in funding.yml

---

src/File/FileHelper.php
tests/PHPStan/File/FileHelperTest.php

Ignore files using a stream wrapper.

---

src/Analyser/Scope.php

https://www.php.net/manual/en/function.zip-entry-read.php states that it may return false.
(First git pull request I do, I hope I'm doing it right.)

Update functionMap.php (zip_entry_read)

---

src/Analyser/NameScope.php
src/PhpDoc/TypeNodeResolver.php
src/Type/FileTypeMapper.php
src/Type/Generic/TemplateTypeScope.php
tests/PHPStan/Analyser/data/generics.php

This allows template types to inherit from the outer scope (outer function / method / class).

Template type inheritance

---

src/Type/TypehintHelper.php

Fixes deprecated call to ReflectionType::__toString()

---

src/Reflection/SignatureMap/functionMap.php

See https://www.php.net/manual/en/imagickdraw.setresolution.php

Fix signature for ImagickDraw::setResolution

---

src/Reflection/SignatureMap/functionMap.php

Set correct return type for Ds\Hashable::hash()

---

README.md

A 3rd-party for banned code: https://github.com/ekino/phpstan-banned-code and https://github.com/phpstan/phpstan-deprecation-rules as a custom.

Update README.md with two new extensions

---

src/PhpDoc/PhpDocNodeResolver.php
src/PhpDoc/ResolvedPhpDocBlock.php
src/PhpDoc/Tag/ExtendsTag.php
src/PhpDoc/Tag/ImplementsTag.php
src/PhpDoc/Tag/UsesTag.php
src/PhpDoc/TypeNodeResolver.php
src/Type/Generic/GenericObjectType.php

This resolves @extends, @implements, and @uses annotations.

Resolve @extends, @implements, @uses annotations

---

src/Reflection/SignatureMap/functionMap.php

Fixed signature of Redis::rawCommand

---

src/Reflection/SignatureMap/functionMap.php

Add missing second signature for setcookie() function

---

src/PhpDoc/TypeNodeResolver.php
src/PhpDoc/TypeNodeResolverFactory.php
src/Reflection/ClassReflection.php
src/Testing/RuleTestCase.php
src/Type/Generic/GenericObjectType.php
src/Type/ObjectType.php
tests/PHPStan/Analyser/AnalyserTest.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Broker/BrokerTest.php
tests/PHPStan/Reflection/ClassReflectionTest.php
tests/PHPStan/Reflection/data/GenericInheritance.php
tests/PHPStan/Rules/PhpDoc/IncompatiblePropertyPhpDocTypeRuleTest.php

Adds basic generic support in ClassReflection, particularly around inheritance. Support for traits, and for methods/properties will be added later.

Class reflection: generic inheritance

---

src/Type/Php/ParseUrlFunctionDynamicReturnTypeExtension.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php

Fix #2072: parse_url can return false

---

README.md
build/composer-require-checker.json
conf/config.neon
src/Command/ErrorFormatter/GitlabErrorFormatter.php
tests/PHPStan/Command/ErrorFormatter/GitlabFormatterTest.php

Gitlab support widget "Code Quality" like Code Climate specification.
More information about Code Quality you can found https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html

Added new error formatter for display errors on gitlab widget.

---

src/Reflection/PhpDefect/PhpDefectClassReflectionExtension.php

See [this example](https://3v4l.org/vCQNi).

Doctype can be null

---

src/Rules/Classes/InstantiationRule.php
tests/PHPStan/Rules/Classes/InstantiationRuleTest.php
tests/PHPStan/Rules/Classes/data/instantiation.php

Fixes https://github.com/phpstan/phpstan/issues/2406

Check constructor arguments when using new $object()

---

src/Rules/Variables/VariableCertaintyInIssetRule.php
tests/PHPStan/Rules/Variables/VariableCertaintyInIssetRuleTest.php
tests/PHPStan/Rules/Variables/data/variable-certainty-isset.php

Add error for this case:
https://phpstan.org/r/d72fd829-845b-4b70-a950-4d080836a113

Add error when variable in isset is always null

---

src/Rules/Cast/EchoRule.php
src/Rules/Cast/InvalidCastRule.php
src/Rules/Cast/InvalidPartOfEncapsedStringRule.php
src/Rules/Cast/PrintRule.php
src/Rules/DeadCode/NoopRule.php
src/Rules/DeadCode/UnreachableStatementRule.php
src/Rules/Generators/YieldFromTypeRule.php
src/Rules/Generators/YieldInGeneratorRule.php
src/Rules/Generators/YieldTypeRule.php
src/Rules/Namespaces/ExistingNamesInGroupUseRule.php
src/Rules/Operators/InvalidBinaryOperationRule.php
src/Rules/Operators/InvalidComparisonOperationRule.php
src/Rules/Operators/InvalidIncDecOperationRule.php
src/Rules/Operators/InvalidUnaryOperationRule.php
tests/PHPStan/Rules/Namespaces/ExistingNamesInGroupUseRuleTest.php

Adopted some rules to report more precise line numbers for errors

---

tests/PHPStan/Rules/Functions/CallToFunctionParametersRuleTest.php
tests/PHPStan/Rules/Functions/data/function-with-nullable-variadic-parameters.php
tests/PHPStan/Rules/Functions/data/function-with-variadic-parameters.php

I was going to fix this, but the tests were already green. All I added was the coverage.
https://github.com/phpstan/phpstan/issues/1098

Test coverage for #1098

---

src/Type/ObjectType.php

Replaces calls to `Broker::getInstance()->getClass()` by a call to `$this->getClassReflection()` everywhere in `ObjectType` / `GenericObjectType`. This makes sure that all uses of `ClassReflection` take generic types into account (the effect of this will be more visible when `getProperty()` / `getMethod()` return resolved types). This also simplifies the code at some places.
Next PRs will be about isSuperTypeOf / accept, and then about resolving types properties / method signatures.

Use getClassReflection()

---

src/Analyser/Scope.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Analyser/data/binary.php
tests/PHPStan/Rules/Methods/data/returnTypes.php

Fix https://github.com/phpstan/phpstan/issues/1709

Fix sum of const and scalar value has wrong type

---

src/Rules/Operators/InvalidComparisonOperationRule.php
tests/PHPStan/Rules/Operators/InvalidComparisonOperationRuleTest.php
tests/PHPStan/Rules/Operators/data/invalid-comparison.php

Please check if my `isArrayType` logic correct. Also, please check if any other test cases should be added.
Closes #2437

Array vs scalar comparison inspection

---

src/Analyser/MutatingScope.php
src/Analyser/NodeScopeResolver.php
src/PhpDoc/PhpDocBlock.php
src/Reflection/ClassReflection.php
src/Reflection/Php/PhpClassReflectionExtension.php
src/Reflection/Php/PhpPropertyReflection.php
src/Reflection/ResolvedFunctionVariant.php
src/Reflection/ResolvedMethodReflection.php
src/Reflection/ResolvedPropertyReflection.php
src/Type/Generic/GenericObjectType.php
tests/PHPStan/Analyser/data/generics.php

This adds support for generics on method call and property fetch expressions

Resolve the type of method calls and property fetches in generic objects

---

src/Reflection/SignatureMap/functionMap.php

fix ZipArchive::locateName definition

---

src/Reflection/SignatureMap/functionMap.php

See: https://www.php.net/manual/en/reflectionclass.construct.php

Define argument type of ReflectionClass::__construct

---

tests/PHPStan/Analyser/data/generics.php

This adds a test for @template annotation on instance methods.

Add test for templates on instance method

---

build/phpstan.neon
src/Analyser/MutatingScope.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Analyser/data/integer-range-types.php
tests/PHPStan/Rules/Comparison/BooleanAndConstantConditionRuleTest.php
tests/PHPStan/Rules/Comparison/data/boolean-and.php
tests/PHPStan/Rules/Comparison/data/if-condition.php

WIP: MutatingScope: use IntegerRangeType to improve comparison handlign

---

conf/config.neon
src/Analyser/NodeScopeResolver.php
src/Testing/RuleTestCase.php
tests/PHPStan/Analyser/AnalyserTest.php
tests/PHPStan/Analyser/NodeScopeResolverTest.php
tests/PHPStan/Analyser/data/early-termination-defined.php
tests/PHPStan/Analyser/data/early-termination.php

I tried to add support for configuring early terminating function calls. Basically, I copied the functionality of the early terminating method calls.
This is my first time working on PHPStan. So please let me know if this is the right approach or not.

Adds support for early terminating function calls

---

.github/ISSUE_TEMPLATE/Function_signature_mismatch.md

Points the users to phpstan/phpstan-src where the pull request should be created.

Updated function signature mismatch template

---

README.md

Add the JUnit formatter into README.md

Add JUnit formatter in readme

---

README.md

Followup for https://github.com/phpstan/phpstan/pull/2744

Fix grammar mistake in README

---

website/app.pcss
website/index.html

Website: polishing

---

composer.json

Conflict with phpstan-shim

---

website/src/writing-php-code/phpdoc-types.md

I was looking for the right syntax to use for these, and though it would be handy to add it in the docs.

Added syntax for variadic functions.

---

website/src/index.njk

Website: improve layout, spaces -> tabs

---

website/src/developing-extensions/class-reflection-extensions.md

From https://github.com/phpstan/phpstan-src/blob/master/src/Reflection/MethodReflection.php

Fix docs on MethodReflection

---

website/src/developing-extensions/class-reflection-extensions.md

From https://github.com/phpstan/phpstan/pull/3935#issuecomment-706939672

Update PropertyReflection in docs

---

website/src/writing-php-code/phpdoc-types.md

adds docs for phpstan/phpstan-src#460

Document local type aliases

---

.github/workflows/build.yml

This allows reproducing the failing test for #4881

Fix e2e test for opcache issue

---

website/src/user-guide/output-format.md

Your explanation here is certainly better than mine at https://github.com/phpstan/phpstan/pull/5011 ;-)
I'm just adding the protocol registration hint, since this took me some time to figure it out...

Adding hint to register the protocol

---

website/src/_posts/bring-your-exceptions-under-control.md

- ref: https://github.com/phpstan/phpstan/discussions/5034

fix checked exceptions example typo

---

website/src/_posts/bring-your-exceptions-under-control.md

Details in https://github.com/phpstan/phpstan/discussions/5034

Align Logic/Runtime exception examples with PHP documentation

---

website/src/config-reference.md

inspired from https://phpstan.org/blog/phpstan-is-ready-for-php8

document `phpVersion` config parameter

---

website/src/user-guide/command-line-usage.md

Current docs are a bit confusing.

Clarify the Xdebug flag

---

website/src/_posts/solving-phpstan-no-value-type-specified-in-iterable-type.md

replace link from discovering symbols to stub files

fix link in documentation

---

.github/workflows/build-issue-bot.yml
.github/workflows/extension-tests.yml
.github/workflows/integration-tests.yml
.github/workflows/other-tests.yml
.github/workflows/run-issue-bot.yml
.github/workflows/tests.yml
.github/workflows/update-playground-runner.yml
e2e/test-extension.sh

This has no effect since Composer 2, see https://github.com/composer/composer/commit/a0c5d519e985009fc6a50df03cffb6b886674ffa

Remove deprecated Composer --no-suggest usage

---

website/src/user-guide/extension-library.md

Add phpstan-magento to the extension list.

Add phpstan-magento to the extension list

---

website/src/writing-php-code/phpdoc-types.md

Fixes #5498. Changes are pretty self-explanatory.

Clarify "Other advanced string types" docs.

---

website/src/developing-extensions/dependency-injection-configuration.md

Clarify dependency injection configuration documentation
